url: http://alizalau.github.io
baseurl: 

# Site Settings
title: Aliza Lau
description: Software Developer
keywords: "jekyll, theme"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.png"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]
